FROM node:16 as fe-builder

RUN apt update && \
    apt install curl unzip -y \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install

COPY ts-redux-react-realworld-example-app /app
WORKDIR /app
RUN npm clean-install
RUN npm run build




